// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCvHuYdDYgnv9L2yznt2m2RWndKL6T7dM',
    appId: '1:837477271540:web:952405f6b6956c8d775ba1',
    messagingSenderId: '837477271540',
    projectId: 'project1-c8b30',
    authDomain: 'project1-c8b30.firebaseapp.com',
    storageBucket: 'project1-c8b30.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPPzkId0ZV0hyXghNyFlaJ4zyQAMHJLN0',
    appId: '1:837477271540:android:9794cc0baaf0a2e3775ba1',
    messagingSenderId: '837477271540',
    projectId: 'project1-c8b30',
    storageBucket: 'project1-c8b30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVU2BoPp_MPe4WX2DGIpUfXiMnWZQVLjA',
    appId: '1:837477271540:ios:85ed2b659f0dc740775ba1',
    messagingSenderId: '837477271540',
    projectId: 'project1-c8b30',
    storageBucket: 'project1-c8b30.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVU2BoPp_MPe4WX2DGIpUfXiMnWZQVLjA',
    appId: '1:837477271540:ios:85ed2b659f0dc740775ba1',
    messagingSenderId: '837477271540',
    projectId: 'project1-c8b30',
    storageBucket: 'project1-c8b30.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCvHuYdDYgnv9L2yznt2m2RWndKL6T7dM',
    appId: '1:837477271540:web:f4fdd5e6604f1cb4775ba1',
    messagingSenderId: '837477271540',
    projectId: 'project1-c8b30',
    authDomain: 'project1-c8b30.firebaseapp.com',
    storageBucket: 'project1-c8b30.firebasestorage.app',
  );
}
